CREATE TABLE IF NOT EXISTS `empresas` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `nome` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255),
    `cnpj` VARCHAR(18),
    `telefone` VARCHAR(15),
    `endereco` VARCHAR(255),
    `cidade` VARCHAR(255),
    `estado` VARCHAR(255),
    `cep` VARCHAR(10),
    `data_criado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `data_atualizado` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
